"""
Django settings for Railway deployment.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-0p)0*02a&slp77h$if=%r%xne#z@sl1g&@e@q#0za5q!i%vuh&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '*.railway.app',
    '.railway.app',
    'backend-sk-final-production.up.railway.app',
    'backend-sk-final-production-d5dd.up.railway.app',
    'sergeykhan-backend-production.up.railway.app'
]

# CSRF settings for Railway deployment
csrf_origins_str = config('CSRF_TRUSTED_ORIGINS', default="")
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',')]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://backend-sk-final-production.up.railway.app',
        'https://backend-sk-final-production-d5dd.up.railway.app',
        'https://sergeykhan-backend-production.up.railway.app',
        'https://*.railway.app',
        'https://sergey-khan-web-visitor.vercel.app',   # убран лишний слэш
        'https://sergey-khan-web-gamma.vercel.app',
        'https://*.vercel.app',
        'https://sergey-khan-operator-liard.vercel.app',
        'https://sergey-khan-garant-master.vercel.app',
        'https://sergey-khan-admin.vercel.app',
        'https://sergey-khan-master.vercel.app',
        'https://sergey-khan-curator.vercel.app',
        'https://xanservice.org',
        'https://www.xanservice.org',
    ]

# Security settings for production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False  # Railway handles SSL


# Application definition

INSTALLED_APPS = [
    'corsheaders',                    # <-- must come before rest_framework if you use it
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'api1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',   # MUST be first
    'whitenoise.middleware.WhiteNoiseMiddleware',      # Right after Security for static files
    'corsheaders.middleware.CorsMiddleware',           # Before any response-generating middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Default to SQLite for development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use PostgreSQL on Railway if DATABASE_URL is provided
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL)


# REST framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# CORS configuration
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)

# If not allowing all origins, specify allowed origins
if not CORS_ALLOW_ALL_ORIGINS:
    cors_origins_str = config('CORS_ALLOWED_ORIGINS', default="")
    if cors_origins_str:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_str.split(',')]
    else:
        CORS_ALLOWED_ORIGINS = [
            "http://localhost:3000",
            "http://localhost:3001",
            "http://localhost:3002",
            "http://localhost:3003",
            "http://localhost:3004",
            "http://localhost:3005",
            "http://localhost:3006",
            "http://localhost:3007",
            "http://localhost:3008",
            "http://localhost:3009",
            "https://backend-sk-final-production.up.railway.app",
            "https://backend-sk-final-production-d5dd.up.railway.app",
            "https://sergey-khan-web-gamma.vercel.app",
            "https://sergeykhan-backend-production.up.railway.app",
            # wildcard здесь НЕ работает — перенесён в CORS_ALLOWED_ORIGIN_REGEXES ниже
            "https://sergey-khan-web-visitor.vercel.app",
            "https://sergey-khan-operator-liard.vercel.app",
            "https://sergey-khan-garant-master.vercel.app",
            "https://sergey-khan-admin.vercel.app",
            "https://sergey-khan-master.vercel.app",
            "https://sergey-khan-curator.vercel.app",
            "https://xanservice.org",
            "https://www.xanservice.org",
        ]
        # Wildcard-паттерны для CORS (django-cors-headers поддерживает только regex)
        CORS_ALLOWED_ORIGIN_REGEXES = [
            r"^https://[\w-]+\.railway\.app$",
            r"^https://[\w-]+\.vercel\.app$",
        ]

CORS_ALLOW_CREDENTIALS = True
# (Optional) further tighten or expand headers/methods:
# CORS_ALLOW_HEADERS = [
#     "content-type",
#     "authorization",
#     "x-requested-with",
# ]
# CORS_ALLOW_METHODS = [
#     "GET",
#     "POST",
#     "PUT",
#     "PATCH",
#     "DELETE",
#     "OPTIONS",
# ]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files configuration for WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
AUTH_USER_MODEL = 'api1.CustomUser'